name: nightly

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.clone.outputs.version }}
      commit: ${{ steps.clone.outputs.commit }}

    steps:
      - name: Clone latest GitLab source
        id: clone
        run: |
          git clone https://gitlab.com/gitlab-org/gitlab.git --depth 1
          echo "::set-output name=version::$(cat gitlab/VERSION)"
          echo "::set-output name=commit::$(git -C gitlab rev-parse --short HEAD)"

      - name: Upload yaml doc
        uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci.md
          path: gitlab/doc/ci/yaml/index.md

  build:
    needs: source
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Set up Dashing
        run: brew install dashing

      - name: Download yaml doc
        uses: actions/download-artifact@v2
        with:
          name: gitlab-ci.md
          path: yaml_src

      - name: Build HTML
        run: |
          perl -lape 's|\(([^\)]+)\.md|(https://docs.gitlab.com/ee/ci/yaml/$1.html|g' -i yaml_src/index.md
          bundle exec jekyll build -s yaml_src -d yaml

      - name: Build docset
        run: |
          dashing build --source yaml
          mkdir -p docset
          mv gitlab-ci.docset docset/

      - name: Upload docset
        uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci.docset
          path: docset

  publish:
    needs: [source, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download docset
        uses: actions/download-artifact@v2
        with:
          name: gitlab-ci.docset

      - name: Build tgz archive
        run: tar -cvzf gitlab-ci.tgz gitlab-ci.docset

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: gitlab-ci.tgz
          commit: master
          tag: v${{ needs.source.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  feed:
    needs: [source, publish]
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docset Feed
        run: |
          mkdir feed
          cat > feed/gitlab-ci.xml <<EOL
          <entry>
            <version>${{ needs.source.outputs.commit }}</version>
            <url>https://github.com/xingrz/docset_gitlab-ci/releases/download/v${{ needs.source.outputs.version }}/gitlab-ci.tgz</url>
          </entry>
          EOL

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: feed
          keep_history: true
          allow_empty_commit: false
          build_dir: feed
          commit_message: "Update ${{ needs.source.outputs.version }} (${{ needs.source.outputs.commit }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
