name: nightly

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.fetch.outputs.version }}
      digest: ${{ steps.fetch.outputs.digest }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install tools
        run: npm ci

      - name: Fetch and rebuild page from GitLab
        id: fetch
        run: |
          node fetch.js
          echo "::set-output name=version::$(cat VERSION)"
          echo "::set-output name=digest::$(cat DIGEST)"

      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: keywords
          path: keywords

  build:
    needs: source
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Dashing
        run: brew install dashing

      - name: Download HTML
        uses: actions/download-artifact@v2
        with:
          name: keywords
          path: keywords

      - name: Build docset
        run: |
          dashing build --source keywords
          mkdir -p docset
          mv gitlab-ci.docset docset/

      - name: Upload docset
        uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci.docset
          path: docset

  publish:
    needs: [source, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download docset
        uses: actions/download-artifact@v2
        with:
          name: gitlab-ci.docset

      - name: Build tgz archive
        run: tar -cvzf gitlab-ci.tgz gitlab-ci.docset

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: gitlab-ci.tgz
          commit: master
          tag: v${{ needs.source.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  feed:
    needs: [source, publish]
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docset Feed
        run: |
          mkdir feed
          cat > feed/gitlab-ci.xml <<EOL
          <entry>
            <version>${{ needs.source.outputs.version }} (${{ needs.source.outputs.digest }})</version>
            <url>https://github.com/xingrz/docset_gitlab-ci/releases/download/v${{ needs.source.outputs.version }}/gitlab-ci.tgz</url>
          </entry>
          EOL

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: feed
          keep_history: true
          allow_empty_commit: false
          build_dir: feed
          commit_message: "Update ${{ needs.source.outputs.version }} (${{ needs.source.outputs.digest }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
