name: nightly

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    outputs:
      version: ${{ steps.source.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Set up Dashing
        run: brew install dashing

      - name: Get latest GitLab source
        id: source
        run: |
          wget -q https://gitlab.com/gitlab-org/gitlab/-/archive/master/gitlab-master.zip
          unzip gitlab-master.zip gitlab-master/VERSION gitlab-master/doc/ci/yaml/index.md
          echo "::set-output name=version::$(cat gitlab-master/VERSION)"
          mv gitlab-master/doc/ci/yaml yaml_src

      - name: Build HTML
        run: |
          perl -lape 's|\(([^\)]+)\.md|(https://docs.gitlab.com/ee/ci/yaml/$1.html|g' -i yaml_src/index.md
          bundle exec jekyll build -s yaml_src -d yaml

      - name: Build docset
        run: |
          dashing build --source yaml
          mkdir -p docset
          mv gitlab-ci.docset docset/

      - name: Upload docset
        uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci.docset
          path: docset

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download docset
        uses: actions/download-artifact@v2
        with:
          name: gitlab-ci.docset

      - name: Build tgz archive
        run: tar -cvzf gitlab-ci.tgz gitlab-ci.docset

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: gitlab-ci.tgz
          commit: master
          tag: v${{ needs.build.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
